
# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/news_aggregator
spring.datasource.username=test
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate (PostgreSQL + Flyway)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#JWT
jwt.secret=my-super-secret-key-that-is-very-secure-and-long-enough

news-aggregator-url=https://gnews.io/api/v4
news-aggregator-api-key= ${NEWS_AGGREGATOR_API_KEY}